alias ll='ls -la'
alias g='git'
alias aq='aqua'
alias aqls='aq list | fzf'
alias aqgi='aq g -i'
alias aqia='aq i -l -a'
alias k9s='LC_CTYPE="en_US.UTF-8" k9s'
alias vim='nvim'
alias ssh='TERM=xterm-256color ssh'
