version: 2
commands:
  - command: notepad
    arguments:
      - ${INPUT}
    title: メモ帳

tools:
  eruby-erb: &eruby-erb
    lint-command: 'erb -x -T - | ruby -c'
    lint-stdin: true
    lint-offset: 1
    format-command: htmlbeautifier

  vim-vint: &vim-vint
    lint-command: 'vint'
    lint-stdin: false

  make-checkmake: &make-checkmake
    lint-command: 'checkmake'
    lint-stdin: true

  markdown-markdownlint: &markdown-markdownlint
    lint-command: 'markdownlint -s -c %USERPROFILE%\.markdownlintrc'
    lint-stdin: true
    lint-formats:
      - '%f: %l: %m'

  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -f parsable'
    lint-stdin: true

  python-flake8: &python-flake8
    lint-command: 'flake8 --stdin-display-name ${INPUT}'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  python-mypy: &python-mypy
    lint-command: 'mypy --show-column-numbers'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  python-yapf: &python-yapf
    format-command: 'yapf --style {based_on_style: chromium, indent_width: 20}'

  python-autopep8: &python-autopep8
    format-command: 'autopep8 --max-line-length 120 --experimental'

  python-isort: &python-isort
    format-command: 'isort ${INPUT}'

  eslint-lint: &eslint-lint
    lint-command: './node_modules/.bin/eslint -f unix --stdin ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true

  eslint-format: &eslint-format
    format-command: './node_modules/.bin/eslint -fix ${INPUT}'

  php-phpstan: &php-phpstan
    lint-command: './vendor/bin/phpstan analyze --error-format raw --no-progress'

  html-prettier: &html-prettier
    format-command: './node_modules/.bin/prettier --parser html'

  css-prettier: &css-prettier
    format-command: './node_modules/.bin/prettier --parser css'

  json-prettier: &json-prettier
    format-command: './node_modules/.bin/prettier --parser json'

  javascript-prettier: &javascript-prettier
    format-command: './node_modules/.bin/prettier'
  
  typescript-prettier: &typescript-prettier
    format-command: './node_modules/.bin/prettier --parser typescript'

  json-jq: &json-jq
    lint-command: 'jq .'

  json-fixjson: &json-fixjson
    format-command: 'fixjson'

  csv-csvlint: &csv-csvlint
    lint-command: 'csvlint'

  any-excitetranslate: &any-excitetranslate
    hover-command: 'excitetranslate'
    hover-stdin: true

languages:
  eruby:
    - <<: *eruby-erb

  vim:
    - <<: *vim-vint

  make:
    - <<: *make-checkmake

  markdown:
    - <<: *markdown-markdownlint

  yaml:
    - <<: *yaml-yamllint

  python:
    - <<: *python-flake8
    - <<: *python-isort
    - <<: *python-mypy
    - <<: *python-autopep8

  javascript:
    - <<: *eslint-lint
    - <<: *eslint-format
    - <<: *javascript-prettier
  
  javascriptreact:
    - <<: *eslint-lint
    - <<: *eslint-format
    - <<: *javascript-prettier

  typescript:
    - <<: *eslint-lint
    - <<: *eslint-format
    - <<: *typescript-prettier
  
  typescriptreact:
    - <<: *eslint-lint
    - <<: *eslint-format
    - <<: *typescript-prettier

  php:
    - <<: *php-phpstan

  html:
    - <<: *html-prettier

  css:
    - <<: *css-prettier

  json:
    - <<: *json-jq
    - <<: *json-fixjson
    # - <<: *json-prettier

  csv:
    - <<: *csv-csvlint

  _:
    - <<: *any-excitetranslate
