add_newline = true
scan_timeout = 10

# A minimal left prompt
format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status
$character"""

# move the rest of the prompt to the right
right_format = """
$username\
$hostname\
$shlvl\
$singularity\
$vcsh\
$hg_branch\
$docker_context\
$package\
$cmake\
$cobol\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$kubernetes\
$openstack\
$env_var\
$crystal\
$custom\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell"""

[aws]
disabled = true

[kubernetes]
format = 'on [⛵ $context \($namespace\)](dimmed green) '
disabled = true
[kubernetes.context_aliases]
"gke_.*_(?P<cluster>[\\w-]+)" = "gke-$cluster"

[gcloud]
disabled = true
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '
style = "bold blue"

[python]
pyenv_version_name = true
