prSections:
  - title: My Pull Requests
    filters: is:open author:@me
    layout:
      author:
        hidden: false
        # width: <number of columns>
        # grow: <bool> this will make the column grow in size
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
issuesSections:
  - title: Created
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
defaults:
  layout:
    prs:
      repo:
        grow: true,
        width: 10
        hidden: false
    # issues: same structure as prs
  prsLimit: 20 # global limit
  issuesLimit: 20 # global limit
  preview:
    open: true # whether to have the preview pane open by default
    width: 60 # width in columns
  refetchIntervalMinutes: 30 # will refetch all sections every 30 minutes
repoPaths: # configure where to locate repos when checking out PRs
  :owner/:repo: ~/ghq/github.com/:owner/:repo # template if you always clone github repos in a consistent location
keybindings:
  prs:
    - key: R
      command: >
        gh pr checkout {{.PrNumber}} &&
        nvim -c ":DiffviewOpen main...{{.HeadRefName}}"
pager:
  diff: delta # or delta for example
confirmQuit: false # show prompt on quit or not
